CREATE TABLE `iepraw` (
  `id` INT unsigned NOT NULL AUTO_INCREMENT,
  `PublicationDate` VARCHAR(10) CHARACTER SET ascii NOT NULL,
  `countryName` VARCHAR(20) CHARACTER SET ascii NOT NULL,
  `reportingYear` SMALLINT unsigned NOT NULL,
  `EPRTR_SectorCode` TINYINT unsigned,
  `EPRTR_SectorName` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `EPRTRAnnexIMainActivity` VARCHAR(16) CHARACTER SET ascii NOT NULL,
  `FacilityInspireId` VARCHAR(256) NOT NULL,
  `facilityName` VARCHAR(512) NOT NULL,
  `city` VARCHAR(128) NOT NULL,
  `Longitude` VARCHAR(32) CHARACTER SET ascii NOT NULL,
  `Latitude` VARCHAR(32) CHARACTER SET ascii NOT NULL,
  `addressConfidentialityReason` VARCHAR(32) CHARACTER SET ascii NOT NULL,
  `TargetRelease` VARCHAR(8) CHARACTER SET ascii NOT NULL,
  `Pollutant` VARCHAR(128) CHARACTER SET ascii NOT NULL,
  `Releases` BIGINT unsigned NOT NULL,
  `confidentialityReason` VARCHAR(16) CHARACTER SET ascii NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
