#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD
#
# Compares emissions from ETS and Industrial Reporting data

import argparse

import MySQLdb
import MySQLdb.cursors
import pandas
import plotly.express


def getdata(db, inspireid, n2o=False, start=0, end=9999):
    db.execute("SELECT * FROM linking WHERE iep=%s", (inspireid,))
    linking = db.fetchone()
    etscountry, etsid = linking["ets"].split("_")

    db.execute("SELECT * FROM ets WHERE "
               "REGISTRY_CODE=%s AND INSTALLATION_IDENTIFIER=%s",
               (etscountry, etsid))

    etsdata = {}
    for k, v in db.fetchone().items():
        if k.startswith("VERIFIED_EMISSIONS_"):
            if v == -1:
                continue
            year = int(k.split("_")[-1])
            if year < start or year > end:
                continue
            etsdata[year] = v

    db.execute("SELECT year,releases FROM prtr "
               "WHERE pollutant='CO2' AND inspireid=%s",
               (inspireid,))

    iredata = {}
    for d in db.fetchall():
        year = int(d["year"])
        if year < start or year > end:
            continue
        iredata[year] = d["releases"] / 1000  # industrial reporting is in kg, ets in t

    if n2o:
        db.execute("SELECT year,releases FROM prtr "
                   "WHERE pollutant='N2O' AND inspireid=%s",
                   (inspireid,))
        for d in db.fetchall():
            year = int(d["year"])
            if year < start or year > end:
                continue
            if year <= 2012:
                # https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32009D0073
                n2ogwpfactor = 310
            elif 2013 <= year <= 2020:
                # table 6 at
                # https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2012:181:0030:0104:en:PDF
                n2ogwpfactor = 310
            elif year >= 2021:
                # see https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32020R2085
                n2ogwpfactor = 265

            if year not in iredata:
                iredata[year] = 0
            # divide by 1000 because industrial reporting is in kg, ets in t
            iredata[year] = (d["releases"] * n2ogwpfactor) / 1000

    dat = {"Emission Trading System": etsdata, "Industrial Emissions Portal": iredata}
    return pandas.DataFrame(dat).sort_index()


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("inspireid", help="ID in industrial reporting FacilityInspireId")
    ap.add_argument("-d", "--debug", action="store_true")
    ap.add_argument("-n", "--n2o", action="store_true")
    ap.add_argument("-s", "--start", type=int, default=0, help="Start year")
    args = ap.parse_args()

    c = MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, host="127.0.0.1",
                        database="eu", user="ghg").cursor()

    cdata = getdata(c, args.inspireid, start=args.start, n2o=args.n2o)

    fig = plotly.express.line(cdata, markers=True)
    unit = "tCO₂"
    if args.n2o:
        unit = "tCO₂eq"
    fig.update_layout(yaxis_title=unit, xaxis_title="year")
    fig.update_yaxes(rangemode="tozero")
    fig.update_traces(connectgaps=True)
    fig.show()
