#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD

import argparse
import sys

import MySQLdb
import MySQLdb.cursors
import pandas
import plotly.express

ap = argparse.ArgumentParser()
ap.add_argument("facilityids", nargs="+")
ap.add_argument("-t", "--type", help="Type of emission (Default: CO2)")
args = ap.parse_args()

if not args.type or args.type.lower() == "co2":
    ptype = "Carbon dioxide (CO2)"
elif args.type.lower() == "sf6":
    ptype = "Sulphur hexafluoride (SF6)"
else:
    sys.exit("Currently unsupported emission type")

c = MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, host="127.0.0.1",
                    database="ghg", user="ghg", password="ghg").cursor()  # noqa: S106

dat = {}
for facilityid in args.facilityids:
    c.execute("SELECT reportingYear,Releases,facilityName FROM eu "
              "WHERE Pollutant=%s AND FacilityInspireId=%s"
              "ORDER BY reportingYear",
              (ptype, facilityid))

    company = {}
    cdata = c.fetchall()
    if not cdata:
        sys.exit(f"No data for {facilityid}")
    d = {}  # pylint workaround...
    for d in cdata:
        year = int(d["reportingYear"])
        company[year] = d["Releases"]
    # FIXME prevent name collissions
    dat[d["facilityName"]] = company
dat = pandas.DataFrame(dat).sort_index()

fig = plotly.express.line(dat, markers=True)
fig.update_layout(yaxis_title="kgCO2", xaxis_title="year")
fig.update_yaxes(rangemode="tozero")
fig.update_traces(connectgaps=True)
fig.show()
