#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD

import argparse
import json
import os
import pathlib
import sys

import MySQLdb
import MySQLdb.cursors
import pandas
import plotly.express

ap = argparse.ArgumentParser()
ap.add_argument("facilityids", nargs="+")
ap.add_argument("-t", "--type", default="CO2", help="Type of emission (Default: CO2)")
ap.add_argument("-b", "--bar", action="store_true", help="Use bar chart")
ap.add_argument("--html", help="Write HTML file")
args = ap.parse_args()

ppath = os.path.abspath(os.path.join(os.path.dirname(__file__), "../pollutantshort.json"))
pshort = json.loads(pathlib.Path(ppath).read_text())

c = MySQLdb.connect(cursorclass=MySQLdb.cursors.DictCursor, host="127.0.0.1",
                    database="eu", user="ghg").cursor()

dat = {}
for facilityid in args.facilityids:
    c.execute("SELECT year,releases,name FROM iep "
              "WHERE pollutant=%s AND inspireid=%s"
              "ORDER BY year",
              (args.type, facilityid))

    company = {}
    cdata = c.fetchall()
    if not cdata:
        sys.exit(f"No data for {facilityid}")
    d = {}  # pylint workaround...
    for d in cdata:
        year = int(d["year"])
        company[year] = d["releases"]
    # FIXME prevent name collissions
    dat[d["name"]] = company
dat = pandas.DataFrame(dat).sort_index()

if args.bar:
    fig = plotly.express.bar(dat)
    fig.update_layout(yaxis_title=f"kg{args.type}", xaxis_title="year")
    # Examples to adapt layout:
    # fig.update_layout(showlegend=False)  # noqa: ERA001
    # fig.update_layout(font_family="Roboto Black", font={"size": 50})  # noqa: ERA001
    # fig.update_traces(marker_color="orange")  # noqa: ERA001
else:
    fig = plotly.express.line(dat, markers=True)
    fig.update_layout(yaxis_title=f"kg{args.type}", xaxis_title="year")
    fig.update_yaxes(rangemode="tozero")
    fig.update_traces(connectgaps=True)
fig.update_xaxes(dtick="Y1")
if args.html:
    fig.write_html(args.html, full_html=False, include_plotlyjs=False)
else:
    fig.show()
